---
blackbox_exporter_version: "0.25.0"
blackbox_exporter_arch: amd64
blackbox_exporter_user: blackbox_exporter
blackbox_exporter_bin: /usr/local/bin/blackbox_exporter
blackbox_exporter_config_dir: /etc/blackbox_exporter
blackbox_exporter_port: 9115
